export enum AssinaturaBillingType {
  SUBSCRIPTION = "subscription",
  UPGRADE_PLAN = "upgrade_plan",
  UPGRADE = "upgrade",
  DOWNGRADE = "downgrade",
  ACTIVATION = "activation",
  EXPANSION = "expansion",
  RENEWAL = "renewal",
}

export enum PrecoOrigem {
  NORMAL = "normal",
  PROMOCIONAL = "promocional",
  PERSONALIZADO = "personalizado",
}

export enum AssinaturaStatus {
  ATIVA = "ativa",
  TRIAL = "trial",
  SUSPENSA = "suspensa",
  PENDENTE_PAGAMENTO = "pendente_pagamento",
  CANCELADA = "cancelada"
}

export enum CobrancaStatus {
  PAGO = "pago",
  PENDENTE = "pendente"
}

export enum AssinaturaCobrancaStatus {
  PAGO = "pago",
  PENDENTE_PAGAMENTO = "pendente_pagamento",
  CANCELADA = "cancelada"
}

export enum CobrancaTipoPagamento {
  DINHEIRO = "dinheiro",
  CARTAO_CREDITO = "cartao-credito",
  CARTAO_DEBITO = "cartao-debito",
  TRANSFERENCIA = "transferencia",
  PIX = "PIX",
  BOLETO = "boleto"
}

export enum AssinaturaTipoPagamento {
  PIX = "PIX",
}

export enum CobrancaOrigem {
  MANUAL = "manual",
  AUTOMATICA = "automatica",
}

export enum CobrancaTipo {
  MENSALIDADE = "mensalidade",
  AVULSA = "avulsa"
}

export enum PassageiroDesativacaoCobrancaAutomaticaMotivo {
  MANUAL = "manual",
  AUTOMATICA = "automatica",
}

export enum UserType {
  ADMIN = "admin",
  MOTORISTA = "motorista",
}

export enum WhatsappStatus {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  CONNECTING = "CONNECTING",
  OPEN = "open", // Evolution API uses lowercase 'open'
  UNKNOWN = "UNKNOWN",
  NOT_FOUND = "NOT_FOUND"
}

export enum PixKeyStatus {
  VALIDADA = "VALIDADA",
  NAO_CADASTRADA = "NAO_CADASTRADA",
  INVALIDADA_POS_FALHA = "INVALIDADA_POS_FALHA",
  PENDENTE_VALIDACAO = "PENDENTE_VALIDACAO",
  FALHA_VALIDACAO = "FALHA_VALIDACAO"
}

export enum TransactionStatus {
  SUCESSO = "SUCESSO",
  ERRO = "ERRO",
  EM_PROCESSAMENTO = "EM_PROCESSAMENTO_BANCARIO",
  PROCESSAMENTO = "PROCESSAMENTO",
  AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO",
  PENDENTE = "PENDENTE"
}

export enum RepasseStatus {
  PENDENTE = "PENDENTE",
  PROCESSANDO = "PROCESSANDO",
  AGUARDANDO_APROVACAO = "AGUARDANDO_APROVACAO",
  EM_PROCESSAMENTO = "EM_PROCESSAMENTO_BANCARIO",
  REPASSADO = "REPASSADO",
  FALHA = "FALHA_REPASSE"
}

export enum RepasseState {
  CRIADO = 'CRIADO',
  DECODIFICANDO = 'DECODIFICANDO',
  DECODIFICADO = 'DECODIFICADO',
  SUBMETIDO = 'SUBMETIDO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  EM_LIQUIDACAO = 'EM_LIQUIDACAO',
  LIQUIDADO = 'LIQUIDADO',
  ERRO_DECODIFICACAO = 'ERRO_DECODIFICACAO',
  ERRO_TRANSFERENCIA = 'ERRO_TRANSFERENCIA',
  EXPIRADO = 'EXPIRADO',
  CANCELADO = 'CANCELADO',
}

export enum PixKeyType {
  CPF = "CPF",
  CNPJ = "CNPJ",
  TELEFONE = "TELEFONE",
  EMAIL = "EMAIL",
  ALEATORIA = "ALEATORIA"
}

export enum ConfigKey {
  PRO_RATA_DIAS_MES = "PRO_RATA_DIAS_MES",
  PRO_RATA_VALOR_MINIMO = "PRO_RATA_VALOR_MINIMO",
  VALOR_INCREMENTO_PASSAGEIRO_EXCESSO = "VALOR_INCREMENTO_PASSAGEIRO_EXCESSO",
  DIA_GERACAO_MENSALIDADES = "DIA_GERACAO_MENSALIDADES",
  DIAS_ANTECEDENCIA_AVISO_VENCIMENTO = "DIAS_ANTECEDENCIA_AVISO_VENCIMENTO",
  DIAS_ANTECEDENCIA_RENOVACAO = "DIAS_ANTECEDENCIA_RENOVACAO",
  TRIAL_DIAS_ESSENCIAL = "TRIAL_DIAS_ESSENCIAL",
  PIX_EXPIRACAO_SEGUNDOS = "PIX_EXPIRACAO_SEGUNDOS",
  PIX_VALIDADE_APOS_VENCIMENTO = "PIX_VALIDADE_APOS_VENCIMENTO",
  DIAS_COBRANCA_POS_VENCIMENTO = "DIAS_COBRANCA_POS_VENCIMENTO",
  ACTIVE_GATEWAY = "ACTIVE_GATEWAY"
}

export enum PaymentGateway {
  INTER = "inter",
  C6 = "c6",
}

export enum ContratoStatus {
  PENDENTE = "pendente",
  ASSINADO = "assinado",
  SUBSTITUIDO = "substituido"
}

export enum PassageiroModalidade {
  IDA = "ida",
  VOLTA = "volta",
  IDA_VOLTA = "ida_volta"
}

export enum PassageiroGenero {
  MASCULINO = "masculino",
  FEMININO = "feminino",
  PREFIRO_NAO_INFORMAR = "prefiro_nao_informar"
}

export enum ParentescoResponsavel {
  PAI = "pai",
  MAE = "mae",
  AVO = "avo",
  TIO = "tio",
  IRMAO = "irmao",
  PRIMO = "primo",
  PADRASTRO = "padrastro",
  MADRASTA = "madrasta",
  RESPONSAVEL_LEGAL = "responsavel_legal",
  OUTRO = "outro"
}

export enum ContratoProvider {
  INHOUSE = "inhouse",
  ASSINAFY = "assinafy",
  DOCUSIGN = "docusign"
}

export enum ContractMultaTipo {
  PERCENTUAL = "percentual",
  FIXO = "fixo"
}

export enum PeriodoEnum {
  MANHA = "manha",
  TARDE = "tarde",
  NOITE = "noite",
  INTEGRAL = "integral"
}

export enum ProviderTransferStatus {
  REALIZADO = "REALIZADO",
  PAGO = "PAGO",
  REJEITADO = "REJEITADO",
  DEVOLVIDO = "DEVOLVIDO",
  FALHA = "FALHA",
  WAITING_APPROVAL = "WAITING_APPROVAL",
  PROCESSING_BANK = "PROCESSING_BANK",
  CANCELADO = "CANCELADO"
}

export enum C6TransferStatus {
  READ_DATA = "READ_DATA",
  ERROR = "ERROR",
  DECODE_ERROR = "DECODE_ERROR",
  PROCESSED = "PROCESSED",
  SCHEDULED = "SCHEDULED",
  PROCESSING = "PROCESSING",
  SCHEDULING_CANCELLED = "SCHEDULING_CANCELLED",
  CANCELED = "CANCELED" // Mantido por precaução caso ainda seja usado em outras respostas antigas
}

export enum InterTransferStatus {
  APROVACAO = "APROVACAO",
  PROCESSADO = "PROCESSADO",
  AGENDADO = "AGENDADO"
}

export enum AtividadeEntidadeTipo {
  COBRANCA = "COBRANCA",
  PASSAGEIRO = "PASSAGEIRO",
  USUARIO = "USUARIO",
  GASTO = "GASTO",
  VEICULO = "VEICULO",
  ESCOLA = "ESCOLA",
  ASSINATURA = "ASSINATURA",
  CONTRATO = "CONTRATO",
}

export enum AtividadeAcao {
  // Financeiro
  COBRANCA_CRIADA = "COBRANCA_CRIADA",
  COBRANCA_EDITADA = "COBRANCA_EDITADA",
  COBRANCA_EXCLUIDA = "COBRANCA_EXCLUIDA",
  PAGAMENTO_MANUAL = "PAGAMENTO_MANUAL",
  PAGAMENTO_REVERTIDO = "PAGAMENTO_REVERTIDO",
  BAIXA_BANCARIA = "BAIXA_BANCARIA",
  NOTIFICACAO_WHATSAPP = "NOTIFICACAO_WHATSAPP",
  CONFIG_LEMBRETE = "CONFIG_LEMBRETE",

  // Passageiro
  PASSAGEIRO_CRIADO = "PASSAGEIRO_CRIADO",
  PASSAGEIRO_EDITADO = "PASSAGEIRO_EDITADO",
  PASSAGEIRO_STATUS = "PASSAGEIRO_STATUS",
  PASSAGEIRO_EXCLUIDO = "PASSAGEIRO_EXCLUIDO",
  PRE_CADASTRO_CONCLUIDO = "PRE_CADASTRO_CONCLUIDO",

  // Perfil / Sistema
  CHAVE_PIX_ALTERADA = "CHAVE_PIX_ALTERADA",
  PERFIL_EDITADO = "PERFIL_EDITADO",
  CONTRATO_CONFIG_EDITADA = "CONTRATO_CONFIG_EDITADA",
  CONTRATO_GERADO = "CONTRATO_GERADO",
  CONTRATO_ASSINADO = "CONTRATO_ASSINADO",
  CONTRATO_EXCLUIDO = "CONTRATO_EXCLUIDO",
  ASSINATURA_UPGRADE = "ASSINATURA_UPGRADE",
  ASSINATURA_PAGAMENTO = "ASSINATURA_PAGAMENTO",
  ASSINATURA_DOWNGRADE = "ASSINATURA_DOWNGRADE",
  ASSINATURA_CANCELADA = "ASSINATURA_CANCELADA",
  USUARIO_EXCLUIDO = "USUARIO_EXCLUIDO",
  USUARIO_SUSPENSO = "USUARIO_SUSPENSO",
  WHATSAPP_STATUS_ALTERADO = "WHATSAPP_STATUS_ALTERADO",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  SENHA_ALTERADA = "SENHA_ALTERADA",
  RECUPERACAO_SENHA = "RECUPERACAO_SENHA",

  // Operacional
  GASTO_REGISTRADO = "GASTO_REGISTRADO",
  GASTO_EDITADO = "GASTO_EDITADO",
  GASTO_EXCLUIDO = "GASTO_EXCLUIDO",
  VEICULO_CRIADO = "VEICULO_CRIADO",
  VEICULO_EDITADO = "VEICULO_EDITADO",
  VEICULO_STATUS = "VEICULO_STATUS",
  VEICULO_EXCLUIDO = "VEICULO_EXCLUIDO",
  ESCOLA_CRIADA = "ESCOLA_CRIADA",
  ESCOLA_EDITADA = "ESCOLA_EDITADA",
  ESCOLA_STATUS = "ESCOLA_STATUS",
  ESCOLA_EXCLUIDA = "ESCOLA_EXCLUIDA",
  
  // Jobs
  COBRANCAS_GERADAS = "COBRANCAS_GERADAS",
  LOG_LIMPEZA = "LOG_LIMPEZA"
}
