
// Passenger Events
export const EVENTO_PASSAGEIRO_VENCIMENTO_PROXIMO = "PASSAGEIRO_VENCIMENTO_PROXIMO";
export const EVENTO_PASSAGEIRO_ASSINATURA_VENCEU = "EVENTO_PASSAGEIRO_ASSINATURA_VENCEU";
export const EVENTO_PASSAGEIRO_ATRASADO = "PASSAGEIRO_ATRASADO";
export const EVENTO_PASSAGEIRO_CONTRATO_DISPONIVEL = "PASSAGEIRO_CONTRATO_DISPONIVEL";
export const EVENTO_PASSAGEIRO_CONTRATO_ASSINADO = "PASSAGEIRO_CONTRATO_ASSINADO";

// Driver Events
export const EVENTO_MOTORISTA_TESTE_BOAS_VINDAS = "MOTORISTA_TESTE_BOAS_VINDAS";
export const EVENTO_MOTORISTA_TESTE_EXPIRANDO = "MOTORISTA_TESTE_EXPIRANDO";
export const EVENTO_MOTORISTA_TESTE_ENCERRADO = "MOTORISTA_TESTE_ENCERRADO";

export const EVENTO_MOTORISTA_ASSINATURA_PAGO = "MOTORISTA_ASSINATURA_PAGO";
export const EVENTO_MOTORISTA_ASSINATURA_VENCENDO = "MOTORISTA_ASSINATURA_VENCENDO";
export const EVENTO_MOTORISTA_ASSINATURA_VENCEU = "EVENTO_MOTORISTA_ASSINATURA_VENCEU";
export const EVENTO_MOTORISTA_ASSINATURA_ATRASADA = "MOTORISTA_ASSINATURA_ATRASADA";

export const EVENTO_MOTORISTA_CONTRATO_ASSINADO = "MOTORISTA_CONTRATO_ASSINADO";
export const EVENTO_AUTH_RECUPERACAO_SENHA = "AUTH_RECUPERACAO_SENHA";



// Job Contexts & Flags
export const JOB_CONTEXT_PASSENGER = "passenger";
export const JOB_CONTEXT_SUBSCRIPTION = "subscription";
export const JOB_FLAG_FORCE = "force";
export const JOB_ORIGIN_FORCE = "manual";
export const JOB_ORIGIN_DAILY = "automatica";
export const JOB_ORIGIN_MANUAL = "manual";

// WhatsApp Connection Status
export const WHATSAPP_STATUS = {
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    CONNECTING: "CONNECTING",
    OPEN: "open",
    CLOSE: "close",
    UNKNOWN: "UNKNOWN",
    NOT_FOUND: "NOT_FOUND"
} as const;

export const GLOBAL_WHATSAPP_INSTANCE = "Van360";