
// Passenger Events
export const EVENTO_PASSAGEIRO_VENCIMENTO_PROXIMO = "PASSAGEIRO_VENCIMENTO_PROXIMO" as const;
export const EVENTO_PASSAGEIRO_VENCIMENTO_HOJE = "PASSAGEIRO_VENCIMENTO_HOJE" as const;
export const EVENTO_PASSAGEIRO_ATRASADO = "PASSAGEIRO_ATRASADO" as const;
export const EVENTO_PASSAGEIRO_CONTRATO_DISPONIVEL = "PASSAGEIRO_CONTRATO_DISPONIVEL" as const;
export const EVENTO_PASSAGEIRO_CONTRATO_ASSINADO = "PASSAGEIRO_CONTRATO_ASSINADO" as const;
export const EVENTO_PASSAGEIRO_RECIBO_PAGAMENTO = "PASSAGEIRO_RECIBO_PAGAMENTO" as const;
export const EVENTO_PASSAGEIRO_PIN_RESET = "PASSAGEIRO_PIN_RESET" as const;

// Route Events
export const EVENTO_ROTA_A_CAMINHO_IDA = "ROTA_A_CAMINHO_IDA" as const;
export const EVENTO_ROTA_EMBARCOU_IDA = "ROTA_EMBARCOU_IDA" as const;
export const EVENTO_ROTA_A_CAMINHO_VOLTA = "ROTA_A_CAMINHO_VOLTA" as const;
export const EVENTO_ROTA_DESEMBARCOU_VOLTA = "ROTA_DESEMBARCOU_VOLTA" as const;
export const EVENTO_ROTA_REORDENADA = "ROTA_REORDENADA" as const;

// Driver Events — Trial
export const TRIAL_DURATION_DAYS = 15;
export const EVENTO_MOTORISTA_TESTE_BOAS_VINDAS = "MOTORISTA_TESTE_BOAS_VINDAS" as const;
export const EVENTO_MOTORISTA_TESTE_ENCERRADO = "MOTORISTA_TESTE_ENCERRADO" as const;
export const EVENTO_MOTORISTA_TRIAL_D14_ULTIMO_AVISO = "MOTORISTA_TRIAL_D14_ULTIMO_AVISO" as const;
export const EVENTO_MOTORISTA_TRIAL_RECUPERACAO_1 = "MOTORISTA_TRIAL_RECUPERACAO_1" as const;
export const EVENTO_MOTORISTA_TRIAL_RECUPERACAO_2 = "MOTORISTA_TRIAL_RECUPERACAO_2" as const;

// Driver Events — Assinatura paga
export const EVENTO_MOTORISTA_ASSINATURA_PAGO = "MOTORISTA_ASSINATURA_PAGO" as const;
export const EVENTO_MOTORISTA_ASSINATURA_VENCENDO = "MOTORISTA_ASSINATURA_VENCENDO" as const;
export const EVENTO_MOTORISTA_ASSINATURA_VENCEU = "MOTORISTA_ASSINATURA_VENCEU" as const;
export const EVENTO_MOTORISTA_ASSINATURA_ATRASADA = "MOTORISTA_ASSINATURA_ATRASADA" as const;
export const EVENTO_MOTORISTA_ASSINATURA_FALHA_CARTAO = "MOTORISTA_ASSINATURA_FALHA_CARTAO" as const;
export const EVENTO_MOTORISTA_RENOVACAO_LEMBRETE = "MOTORISTA_RENOVACAO_LEMBRETE" as const;
export const EVENTO_MOTORISTA_RENOVACAO_URGENCIA = "MOTORISTA_RENOVACAO_URGENCIA" as const;
export const EVENTO_MOTORISTA_RENOVACAO_RECUPERACAO_1 = "MOTORISTA_RENOVACAO_RECUPERACAO_1" as const;
export const EVENTO_MOTORISTA_RENOVACAO_RECUPERACAO_FINAL = "MOTORISTA_RENOVACAO_RECUPERACAO_FINAL" as const;

export const EVENTO_MOTORISTA_CONTRATO_ASSINADO = "MOTORISTA_CONTRATO_ASSINADO" as const;
export const EVENTO_AUTH_RECUPERACAO_SENHA = "AUTH_RECUPERACAO_SENHA" as const;
export const EVENTO_AUTH_SENHA_ALTERADA = "AUTH_SENHA_ALTERADA" as const;
export const EVENTO_MOTORISTA_CADASTRO_ADMIN = "MOTORISTA_CADASTRO_ADMIN" as const;
export const EVENTO_MOTORISTA_RESET_SENHA_ADMIN = "MOTORISTA_RESET_SENHA_ADMIN" as const;
export const EVENTO_MOTORISTA_INDICACAO_BONUS = "MOTORISTA_INDICACAO_BONUS" as const;
export const EVENTO_MOTORISTA_INDICACAO_CADASTRO = "MOTORISTA_INDICACAO_CADASTRO" as const;
export const EVENTO_MOTORISTA_ANIVERSARIANTES_SEMANA = "MOTORISTA_ANIVERSARIANTES_SEMANA" as const;
export const EVENTO_MOTORISTA_RESUMO_SEMANAL_PARCELAS = "MOTORISTA_RESUMO_SEMANAL_PARCELAS" as const;
export const EVENTO_MOTORISTA_EQUIPE_CADASTRO = "MOTORISTA_EQUIPE_CADASTRO" as const;
export const EVENTO_MOTORISTA_EQUIPE_RESET_SENHA = "MOTORISTA_EQUIPE_RESET_SENHA" as const;
export const EVENTO_MOTORISTA_EQUIPE_STATUS_ALTERADO = "MOTORISTA_EQUIPE_STATUS_ALTERADO" as const;
export const EVENTO_MOTORISTA_NOVO_PRE_CADASTRO = "MOTORISTA_NOVO_PRE_CADASTRO" as const;
export const EVENTO_MOTORISTA_AUSENCIA_REGISTRADA = "MOTORISTA_AUSENCIA_REGISTRADA" as const;
export const EVENTO_MOTORISTA_AUSENCIA_REMOVIDA = "MOTORISTA_AUSENCIA_REMOVIDA" as const;

// Admin Events
export const EVENTO_ADMIN_NOVO_CADASTRO = "ADMIN_NOVO_CADASTRO" as const;
export const EVENTO_ADMIN_NOVA_ASSINATURA = "ADMIN_NOVA_ASSINATURA" as const;
export const EVENTO_ADMIN_ASSINATURA_CANCELADA = "ADMIN_ASSINATURA_CANCELADA" as const;
export const EVENTO_ADMIN_ASSINATURA_FALHA_PAGAMENTO = "ADMIN_ASSINATURA_FALHA_PAGAMENTO" as const;
export const EVENTO_ADMIN_SISTEMA_ALERTA = "ADMIN_SISTEMA_ALERTA" as const;


// Job Contexts & Flags
export const JOB_CONTEXT_PASSENGER = "passenger";
export const JOB_CONTEXT_SUBSCRIPTION = "subscription";
export const JOB_FLAG_FORCE = "force";
export const JOB_ORIGIN_FORCE = "manual";
export const JOB_ORIGIN_DAILY = "automatica";
export const JOB_ORIGIN_MANUAL = "manual";

// Evolution Connection Status
export const EVOLUTION_STATUS = {
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    CONNECTING: "CONNECTING",
    OPEN: "open",
    CLOSE: "close",
    UNKNOWN: "UNKNOWN",
    NOT_FOUND: "NOT_FOUND"
} as const;

export const EVOLUTION_GLOBAL_INSTANCE = "Van360";

export const FEATURE_FLAGS = {
  ENABLE_LIVE_TRACKING: false
} as const;

export const TRACKING_REALTIME_CONFIG = {
  CHANNEL_PREFIX: "trip-tracking:",
  EVENT_GPS_PING: "gps_ping"
} as const;