
// Passenger Events
export const EVENTO_PASSAGEIRO_VENCIMENTO_PROXIMO = "PASSAGEIRO_VENCIMENTO_PROXIMO" as const;
export const EVENTO_PASSAGEIRO_ASSINATURA_VENCEU = "EVENTO_PASSAGEIRO_ASSINATURA_VENCEU" as const;
export const EVENTO_PASSAGEIRO_ATRASADO = "PASSAGEIRO_ATRASADO" as const;
export const EVENTO_PASSAGEIRO_CONTRATO_DISPONIVEL = "PASSAGEIRO_CONTRATO_DISPONIVEL" as const;
export const EVENTO_PASSAGEIRO_CONTRATO_ASSINADO = "PASSAGEIRO_CONTRATO_ASSINADO" as const;

// Driver Events — Trial
export const EVENTO_MOTORISTA_TESTE_BOAS_VINDAS     = "MOTORISTA_TESTE_BOAS_VINDAS" as const;
export const EVENTO_MOTORISTA_TESTE_EXPIRANDO        = "MOTORISTA_TESTE_EXPIRANDO" as const;
export const EVENTO_MOTORISTA_TESTE_ENCERRADO        = "MOTORISTA_TESTE_ENCERRADO" as const;
export const EVENTO_MOTORISTA_TRIAL_D7_ENGAJADO      = "MOTORISTA_TRIAL_D7_ENGAJADO" as const;
export const EVENTO_MOTORISTA_TRIAL_D7_INATIVO       = "MOTORISTA_TRIAL_D7_INATIVO" as const;
export const EVENTO_MOTORISTA_TRIAL_D14_ULTIMO_AVISO = "MOTORISTA_TRIAL_D14_ULTIMO_AVISO" as const;
export const EVENTO_MOTORISTA_TRIAL_RECUPERACAO_1    = "MOTORISTA_TRIAL_RECUPERACAO_1" as const;
export const EVENTO_MOTORISTA_TRIAL_RECUPERACAO_2    = "MOTORISTA_TRIAL_RECUPERACAO_2" as const;
export const EVENTO_MOTORISTA_TRIAL_RECUPERACAO_FINAL = "MOTORISTA_TRIAL_RECUPERACAO_FINAL" as const;
export const EVENTO_MOTORISTA_TESTE_HOJE             = "MOTORISTA_TESTE_HOJE" as const;

// Driver Events — Assinatura paga
export const EVENTO_MOTORISTA_ASSINATURA_PAGO            = "MOTORISTA_ASSINATURA_PAGO" as const;
export const EVENTO_MOTORISTA_ASSINATURA_VENCENDO        = "MOTORISTA_ASSINATURA_VENCENDO" as const;
export const EVENTO_MOTORISTA_ASSINATURA_VENCEU          = "EVENTO_MOTORISTA_ASSINATURA_VENCEU" as const;
export const EVENTO_MOTORISTA_ASSINATURA_ATRASADA        = "MOTORISTA_ASSINATURA_ATRASADA" as const;
export const EVENTO_MOTORISTA_ASSINATURA_FALHA_CARTAO    = "MOTORISTA_ASSINATURA_FALHA_CARTAO" as const;
export const EVENTO_MOTORISTA_RENOVACAO_LEMBRETE         = "MOTORISTA_RENOVACAO_LEMBRETE" as const;
export const EVENTO_MOTORISTA_RENOVACAO_URGENCIA         = "MOTORISTA_RENOVACAO_URGENCIA" as const;
export const EVENTO_MOTORISTA_RENOVACAO_RECUPERACAO_1    = "MOTORISTA_RENOVACAO_RECUPERACAO_1" as const;
export const EVENTO_MOTORISTA_RENOVACAO_RECUPERACAO_FINAL = "MOTORISTA_RENOVACAO_RECUPERACAO_FINAL" as const;
export const EVENTO_MOTORISTA_CARTAO_COBRANCA_AVISO      = "MOTORISTA_CARTAO_COBRANCA_AVISO" as const;

export const EVENTO_MOTORISTA_CONTRATO_ASSINADO = "MOTORISTA_CONTRATO_ASSINADO" as const;
export const EVENTO_AUTH_RECUPERACAO_SENHA = "AUTH_RECUPERACAO_SENHA" as const;
export const EVENTO_AUTH_SENHA_ALTERADA = "AUTH_SENHA_ALTERADA" as const;



// Job Contexts & Flags
export const JOB_CONTEXT_PASSENGER = "passenger";
export const JOB_CONTEXT_SUBSCRIPTION = "subscription";
export const JOB_FLAG_FORCE = "force";
export const JOB_ORIGIN_FORCE = "manual";
export const JOB_ORIGIN_DAILY = "automatica";
export const JOB_ORIGIN_MANUAL = "manual";

// WhatsApp Connection Status
export const WHATSAPP_STATUS = {
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    CONNECTING: "CONNECTING",
    OPEN: "open",
    CLOSE: "close",
    UNKNOWN: "UNKNOWN",
    NOT_FOUND: "NOT_FOUND"
} as const;

export const GLOBAL_WHATSAPP_INSTANCE = "Van360";